# Importing datasets from databricks fileStore

In [1]:
import datetime
import pandas as pd
from math import *
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Air_compressor data



# The applied options are for CSV files. For other file types, these will be ignored.
df1 = pd.read_csv (r'C:\Users\rnunoo\Documents\Sustainability_DownloadMe\Sustainability_DownloadMe\Sustainability_Dataset\Twinsburg, Ohio\July Data Only\Twinsburg Main Air Compressor.csv')
compressor_data = df1
#dropping irrelevant data 
compressor_data = compressor_data.drop(columns = ['Compressor Total Run Hours (Hours)','Compressed Air Desiccant Dryer Dew Point (F)','Outside_Humidity (% RH)','OutSide_Temp (F)', 'Compressed Air Flow near distribution header (SCFM)','Compressed Air Totalizer near distribution header (m3n)','SampleNumber'])

compressor_data.rename(columns ={'Time Stamp':'Time_Stamp'},inplace = True)

C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (2,3,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
# Production data 


# The applied options are for CSV files. For other file types, these will be ignored.
df2 = pd.read_csv (r'C:\Users\rnunoo\Documents\Sustainability_DownloadMe\Sustainability_DownloadMe\Sustainability_Dataset\Twinsburg, Ohio\July Data Only\Barcode Reflow Oven Scan Times July 2020_1.csv')

production_data = df2
#dropping irrelevant data 
production_data = production_data.drop(columns = ['COMPLETE REASON','CONST TIME','PLANT','AREA','OPERATION','Unique Index'])
production_data.rename(columns ={'PRIOR COMPLETION TIME':'Time_Stamp'},inplace = True)

In [4]:
# Energy usage cost


df3 = pd.read_csv (r'C:\Users\rnunoo\Documents\Sustainability_DownloadMe\Sustainability_DownloadMe\Sustainability_Dataset\Twinsburg, Ohio\July Data Only\julyUsage.csv')

Usage_cost = df3

In [5]:
# Oven trend_data


df4 = pd.read_csv (r'C:\Users\rnunoo\Documents\Sustainability_DownloadMe\Sustainability_DownloadMe\Sustainability_Dataset\Twinsburg, Ohio\July Data Only\July2020 Oven TrendData.csv')

Oven_trend = df4
#Cleaning and reorganizing data
Oven_trend = Oven_trend.iloc[4:]
Oven_trend.columns =['Time_Stamp','Avg_Current_SM1','Avg_Voltage_SM1','Avg_Current_SM4','Avg_Voltage_SM4','Avg_Current_SM7','Avg_Voltage_SM7']

In [6]:
# meter data

df5 = pd.read_csv (r'C:\Users\rnunoo\Documents\Sustainability_DownloadMe\Sustainability_DownloadMe\Sustainability_Dataset\Twinsburg, Ohio\July Data Only\Meter Jan1 to July 28 2020 interval data.csv')
meter_data = df5
meter_data ['Time_Stamp'] = meter_data['Date']+' '+meter_data['Time']
#dropping irrelevant data 
meter_data = meter_data.drop(columns = ['CAP KVAR','CAP KVA','CAP PF','MV90 ID','Rate','Premise','Name','Address','Date','Time','Peak'])

# five dataset
####compressor_data - 1 min time interval - Energy Demand by compressor
####meter_data      - 30 min interval - Facility energy usage
####Oven_trend      - 15 min interval - Energy Demand by three ovens
####Usage_cost*     - monthly cost of energy
####production_data - Time it takes to produce

In [7]:
Usage_cost.head()
##Extract monthly rate from

     DATE   KVAR  c_per_KWH    DEMAND      KWH       cost
0  20-Jul  806.8       8.72  1,345.70  597,299  52,077.58
1  20-Jun  756.0       8.92  1,279.80  528,997  47,160.67
2  20-May  468.7       8.34     843.5  448,229  37,401.86
3  20-Apr  426.6       8.42     813.2  424,903  35,761.24
4  20-Mar  403.9       8.29     812.2  434,717  36,044.62

In [8]:
compressor_data.head()

,Time_Stamp,Compressor Running %,Compressor Motor Current (Amps),Compressed Motor Speed (RPM),Compressor Motor Voltage (Volts),Compressor Discharge Pressure (PSI),Compressed Air Pressure near distribution header (PSI),Compressed Air Stream Temperature near distribution header (F),Unnamed: 15,Unnamed: 16,Unnamed: 17
0,2020-07-01 00:00,70,138,2406,312,114,114.8914,87.42404,NaN,NaN,NaN
1,2020-07-01 00:01,74,138,2406,312,114,114.8913,87.42435,NaN,NaN,NaN
2,2020-07-01 00:02,80,138,2406,312,114,114.8913,87.42466,NaN,NaN,NaN
3,2020-07-01 00:03,80,138,2406,312,114,114.8913,87.42496,NaN,NaN,NaN
4,2020-07-01 00:04,75,138,2406,312,114,114.8912,87.42527,NaN,NaN,NaN

In [9]:
meter_data.head(10)
display(meter_data)

           KW    KVAR       KVA      PF     KWH                Time_Stamp
0      400.68  276.48    486.81  0.8231  200.34      1/1/2020 12:30:00 AM
1      403.92  276.48    489.48  0.8252  201.96       1/1/2020 1:00:00 AM
2      411.48  278.64    496.95   0.828  205.74       1/1/2020 1:30:00 AM
3      408.24  277.56    493.66   0.827  204.12       1/1/2020 2:00:00 AM
4         405  279.72    492.21  0.8228  202.50       1/1/2020 2:30:00 AM
...       ...     ...       ...     ...     ... ..                    ...
10073  867.24  508.68  1,005.42  0.8626  433.62     7/28/2020 10:00:00 PM
10074  827.28  483.84    958.38  0.8632  413.64     7/28/2020 10:30:00 PM
10075  784.08  459.00    908.55   0.863  392.04     7/28/2020 11:00:00 PM
10076     810  473.04    938.01  0.8635  405.00     7/28/2020 11:30:00 PM
10077  791.64  454.68    912.92  0.8671  395.82     7/28/2020 12:00:00 AM

[10078 rows x 7 columns]

In [10]:
production_data.head()

,COMPLETION TIME,TAC TIME MIN,OPTEL SETUP,PART NUMBER,Time_Stamp,IS CHANGEOVER,LINE,ASSEMBLY SIDE
0,7/1/2020 3:37,31.15,SM1:11043,PN-222227,7/1/2020 3:06,Y,SM1,BOT
1,7/1/2020 3:43,5.83,SM1:11043,PN-222227,7/1/2020 3:37,N,SM1,BOT
2,7/1/2020 3:45,2.48,SM1:11043,PN-222227,7/1/2020 3:43,N,SM1,BOT
3,7/1/2020 3:52,7.13,SM1:11043,PN-222227,7/1/2020 3:45,N,SM1,BOT
4,7/1/2020 3:54,1.80,SM1:11043,PN-222227,7/1/2020 3:52,N,SM1,BOT

In [11]:
Oven_trend.head()

,Time_Stamp,Avg_Current_SM1,Avg_Voltage_SM1,Avg_Current_SM4,Avg_Voltage_SM4,Avg_Current_SM7,Avg_Voltage_SM7
4,7/1/2020 0:00,20.28933716,491.8955078,13.72878742,493.8482666,13.93037415,493.4844055
5,7/1/2020 0:15,18.66532135,489.5270996,14.31922913,491.394043,10.72354126,490.9891052
6,7/1/2020 0:30,18.67902565,489.1936951,14.41011524,490.9619446,12.04858112,490.5532227
7,7/1/2020 0:45,12.96404743,492.195343,12.82833099,493.7171936,9.441243172,493.3106384
8,7/1/2020 1:00,18.03351974,491.3703918,14.18379974,493.0763855,17.00906372,492.6877747

## Calculating Energy (KWH)

In [12]:
#Changing datatypes 

Oven_trend['Time_Stamp']=pd.to_datetime(Oven_trend['Time_Stamp'])
Oven_trend['Avg_Current_SM1'] = Oven_trend['Avg_Current_SM1'].astype(float)
Oven_trend['Avg_Current_SM4'] = Oven_trend['Avg_Current_SM4'].astype(float)
Oven_trend['Avg_Current_SM7'] = Oven_trend['Avg_Current_SM7'].astype(float)
Oven_trend['Avg_Voltage_SM1'] = Oven_trend['Avg_Voltage_SM1'].astype(float)
Oven_trend['Avg_Voltage_SM4'] = Oven_trend['Avg_Voltage_SM4'].astype(float)
Oven_trend['Avg_Voltage_SM7'] = Oven_trend['Avg_Voltage_SM7'].astype(float)

## Energy consumed by each oven 
Oven_trend['KWH_SM1'] = (Oven_trend['Avg_Current_SM1']*Oven_trend['Avg_Voltage_SM1'])/250
Oven_trend['KWH_SM4'] = (Oven_trend['Avg_Current_SM4']*Oven_trend['Avg_Voltage_SM4'])/250
Oven_trend['KWH_SM7'] = (Oven_trend['Avg_Current_SM7']*Oven_trend['Avg_Voltage_SM7'])/250

C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\rnunoo\AppData\Local\Continuum\anaconda3.7\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [13]:


compressor_data['Time_Stamp'] = pd.to_datetime(compressor_data['Time_Stamp'])
compressor_data['Compressor Running %'] = compressor_data['Compressor Running %'].astype(float)
compressor_data['Compressor Motor Current (Amps)'] = compressor_data['Compressor Motor Current (Amps)'].astype(float)
compressor_data['Compressed Motor Speed (RPM)'] = compressor_data['Compressed Motor Speed (RPM)'].astype(float)
compressor_data['Compressor Motor Voltage (Volts)'] = compressor_data['Compressor Motor Voltage (Volts)'].astype(float)
compressor_data['Compressor Discharge Pressure (PSI)'] = compressor_data['Compressor Discharge Pressure (PSI)'].astype(float)
compressor_data['Compressed Air Pressure near distribution header (PSI)'] = compressor_data['Compressed Air Pressure near distribution header (PSI)'].astype(float)
compressor_data['Compressed Air Stream Temperature near distribution header (F)'] = compressor_data['Compressed Air Stream Temperature near distribution header (F)'].astype(float)

##Energy consumption by compressor

compressor_data['compressor_KWH'] = (compressor_data['Compressor Motor Current (Amps)']*compressor_data['Compressor Motor Voltage (Volts)'])/60000

#Data aggregation

In [14]:
production_data['Time_Stamp'] = pd.to_datetime(production_data['Time_Stamp'])
production_data_ts = production_data.set_index('Time_Stamp')
df_production = production_data_ts.resample('30Min').mean()
df_production

                     TAC TIME MIN
Time_Stamp
2020-07-01 00:00:00      4.333571
2020-07-01 00:30:00      3.434737
2020-07-01 01:00:00      3.180556
2020-07-01 01:30:00      3.431765
2020-07-01 02:00:00      3.558824
...                           ...
2020-07-31 13:00:00      1.079231
2020-07-31 13:30:00      1.310200
2020-07-31 14:00:00     26.820000
2020-07-31 14:30:00      3.817143
2020-07-31 15:00:00      1.630000

[1471 rows x 1 columns]

In [15]:
#Resampling to 30 min


compressor_data_ts = compressor_data.set_index('Time_Stamp')
df_compressor = compressor_data_ts.resample('30Min').mean()

Oven_trend_ts = Oven_trend.set_index('Time_Stamp')
df_Oventrend = Oven_trend_ts.resample('30Min').mean()

meter_data['Time_Stamp'] = pd.to_datetime(meter_data['Time_Stamp'])
df_meter = meter_data.set_index('Time_Stamp')

In [16]:
df_meter

                         KW    KVAR       KVA      PF     KWH
Time_Stamp
2020-01-01 00:30:00  400.68  276.48    486.81  0.8231  200.34
2020-01-01 01:00:00  403.92  276.48    489.48  0.8252  201.96
2020-01-01 01:30:00  411.48  278.64    496.95   0.828  205.74
2020-01-01 02:00:00  408.24  277.56    493.66   0.827  204.12
2020-01-01 02:30:00     405  279.72    492.21  0.8228  202.50
...                     ...     ...       ...     ...     ... ..
2020-07-28 22:00:00  867.24  508.68  1,005.42  0.8626  433.62
2020-07-28 22:30:00  827.28  483.84    958.38  0.8632  413.64
2020-07-28 23:00:00  784.08  459.00    908.55   0.863  392.04
2020-07-28 23:30:00     810  473.04    938.01  0.8635  405.00
2020-07-28 00:00:00  791.64  454.68    912.92  0.8671  395.82

[10078 rows x 6 columns]

In [25]:
#main1_df = pd.merge(df_compressor,df_Oventrend, how = 'right', on = 'Time_Stamp')
#main1_df = main1_df.set_index('Time_Stamp')
#main_df = pd.merge(main1_df,df_meter, how = 'right', on = 'Time_Stamp')
main1_df = df_compressor.join(df_Oventrend, how='outer').join(df_meter, how='outer')
#main_df = main1_df.join(df_meter, how='outer')
main1_df = main1_df.reset_index()
display(main1_df)

,Time_Stamp,Compressor Running %,Compressor Motor Current (Amps),Compressed Motor Speed (RPM),Compressor Motor Voltage (Volts),Compressor Discharge Pressure (PSI),Compressed Air Pressure near distribution header (PSI),Compressed Air Stream Temperature near distribution header (F),Unnamed: 15,Unnamed: 16,...,Avg_Voltage_SM7,KWH_SM1,KWH_SM4,KWH_SM7,KW,KVAR,KVA,PF,KWH,
0,2020-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,398.52,267.84,480.16,0.83,199.26,
1,2020-01-01 00:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,400.68,276.48,486.81,0.8231,200.34,
2,2020-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,403.92,276.48,489.48,0.8252,201.96,
3,2020-01-01 01:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,411.48,278.64,496.95,0.828,205.74,
4,2020-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,408.24,277.56,493.66,0.827,204.12,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10218,2020-07-31 22:00:00,44.366667,133.200000,1424.166667,195.8,114.833333,117.142120,90.536766,1.833333,64.743617,...,492.991196,14.301327,16.985602,15.022934,NaN,NaN,NaN,NaN,NaN,NaN
10219,2020-07-31 22:30:00,45.066667,132.733333,1453.733333,200.2,114.533333,116.863390,90.882765,1.566667,55.326363,...,493.813293,14.247524,18.063347,13.445566,NaN,NaN,NaN,NaN,NaN,NaN
10220,2020-07-31 23:00:00,39.666667,129.633333,1203.033333,173.3,115.700000,118.391417,90.217521,1.666667,58.857833,...,490.231064,15.775169,14.635923,15.471068,NaN,NaN,NaN,NaN,NaN,NaN
10221,2020-07-31 23:30:00,43.366667,132.700000,1347.433333,194.0,114.766667,117.308960,89.174485,1.566667,55.326363,...,492.302002,14.386418,17.617607,15.394288,NaN,NaN,NaN,NaN,NaN,NaN
10222,2020-08-01 00:00:00,31.000000,133.000000,1003.000000,146.0,114.000000,117.955500,89.267270,0.000000,0.000000,...,493.089752,17.016937,13.438805,16.085573,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
main1_df.to_csv('main.csv', index = False)

In [ ]:
main_df.to_csv('main1_0.csv', index = False)